"""
SQLAlchemy ORM models. One TradingCycle per 15-min window ties together
all BTCSnapshots, the MarketSnapshot, a Prediction, and optionally a Trade.
"""
import enum
from datetime import datetime
from typing import Optional

from sqlalchemy import (
    Boolean, DateTime, Enum, Float, ForeignKey,
    Integer, String, Text, func,
)
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column, relationship


class Base(DeclarativeBase):
    pass


class CycleStatus(str, enum.Enum):
    running = "running"
    completed = "completed"
    error = "error"


class TradeAction(str, enum.Enum):
    YES = "YES"
    NO = "NO"
    SKIP = "SKIP"


class TradeSide(str, enum.Enum):
    yes = "yes"
    no = "no"


class TradeOutcome(str, enum.Enum):
    win = "win"
    loss = "loss"
    pending = "pending"


class TradingCycle(Base):
    """One complete 15-minute Kalshi event cycle."""
    __tablename__ = "trading_cycles"

    id: Mapped[int] = mapped_column(Integer, primary_key=True)
    cycle_start: Mapped[datetime] = mapped_column(DateTime(timezone=True))
    cycle_end: Mapped[Optional[datetime]] = mapped_column(DateTime(timezone=True), nullable=True)
    market_ticker: Mapped[str] = mapped_column(String(100))
    market_title: Mapped[Optional[str]] = mapped_column(String(255), nullable=True)
    target_price: Mapped[Optional[float]] = mapped_column(Float, nullable=True)
    status: Mapped[CycleStatus] = mapped_column(
        Enum(CycleStatus), default=CycleStatus.running
    )
    error_message: Mapped[Optional[str]] = mapped_column(Text, nullable=True)
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now()
    )

    btc_snapshots: Mapped[list["BTCSnapshot"]] = relationship(
        back_populates="cycle", cascade="all, delete-orphan"
    )
    market_snapshot: Mapped[Optional["MarketSnapshot"]] = relationship(
        back_populates="cycle", uselist=False, cascade="all, delete-orphan"
    )
    prediction: Mapped[Optional["PredictionRecord"]] = relationship(
        back_populates="cycle", uselist=False, cascade="all, delete-orphan"
    )
    trade: Mapped[Optional["Trade"]] = relationship(
        back_populates="cycle", uselist=False, cascade="all, delete-orphan"
    )


class BTCSnapshot(Base):
    """BTC on-chain data captured at a point in time within a cycle."""
    __tablename__ = "btc_snapshots"

    id: Mapped[int] = mapped_column(Integer, primary_key=True)
    cycle_id: Mapped[int] = mapped_column(ForeignKey("trading_cycles.id"))
    captured_at: Mapped[datetime] = mapped_column(DateTime(timezone=True))

    # Price data
    price_usd: Mapped[float] = mapped_column(Float)
    price_change_1m: Mapped[Optional[float]] = mapped_column(Float, nullable=True)
    price_change_5m: Mapped[Optional[float]] = mapped_column(Float, nullable=True)
    price_change_10m: Mapped[Optional[float]] = mapped_column(Float, nullable=True)

    # Mempool / on-chain
    mempool_fee_fastest: Mapped[Optional[float]] = mapped_column(Float, nullable=True)
    mempool_fee_half_hour: Mapped[Optional[float]] = mapped_column(Float, nullable=True)
    mempool_size_bytes: Mapped[Optional[int]] = mapped_column(Integer, nullable=True)
    mempool_tx_count: Mapped[Optional[int]] = mapped_column(Integer, nullable=True)
    block_height: Mapped[Optional[int]] = mapped_column(Integer, nullable=True)

    # Derived score used in prediction (-1.0 bearish to +1.0 bullish)
    momentum_score: Mapped[Optional[float]] = mapped_column(Float, nullable=True)

    cycle: Mapped["TradingCycle"] = relationship(back_populates="btc_snapshots")


class MarketSnapshot(Base):
    """Kalshi market state captured just before prediction."""
    __tablename__ = "market_snapshots"

    id: Mapped[int] = mapped_column(Integer, primary_key=True)
    cycle_id: Mapped[int] = mapped_column(ForeignKey("trading_cycles.id"), unique=True)
    captured_at: Mapped[datetime] = mapped_column(DateTime(timezone=True))

    ticker: Mapped[str] = mapped_column(String(100))
    # Prices are in cents (0-100)
    yes_price: Mapped[float] = mapped_column(Float)
    no_price: Mapped[float] = mapped_column(Float)
    yes_volume: Mapped[Optional[int]] = mapped_column(Integer, nullable=True)
    no_volume: Mapped[Optional[int]] = mapped_column(Integer, nullable=True)
    open_interest: Mapped[Optional[int]] = mapped_column(Integer, nullable=True)
    # Close time from Kalshi
    close_time: Mapped[Optional[datetime]] = mapped_column(DateTime(timezone=True), nullable=True)

    cycle: Mapped["TradingCycle"] = relationship(back_populates="market_snapshot")


class PredictionRecord(Base):
    """Prediction generated by the engine for a cycle."""
    __tablename__ = "predictions"

    id: Mapped[int] = mapped_column(Integer, primary_key=True)
    cycle_id: Mapped[int] = mapped_column(ForeignKey("trading_cycles.id"), unique=True)
    predicted_at: Mapped[datetime] = mapped_column(DateTime(timezone=True))

    action: Mapped[TradeAction] = mapped_column(Enum(TradeAction))
    confidence: Mapped[float] = mapped_column(Float)

    # Component scores for debugging and tuning
    btc_score: Mapped[float] = mapped_column(Float)
    kalshi_yes_prob: Mapped[float] = mapped_column(Float)
    combined_score: Mapped[float] = mapped_column(Float)

    # Human-readable breakdown stored as JSON string
    reasoning: Mapped[Optional[str]] = mapped_column(Text, nullable=True)

    cycle: Mapped["TradingCycle"] = relationship(back_populates="prediction")


class Trade(Base):
    """An order placed (paper or real) based on a prediction."""
    __tablename__ = "trades"

    id: Mapped[int] = mapped_column(Integer, primary_key=True)
    cycle_id: Mapped[int] = mapped_column(ForeignKey("trading_cycles.id"), unique=True)
    placed_at: Mapped[datetime] = mapped_column(DateTime(timezone=True))

    ticker: Mapped[str] = mapped_column(String(100))
    side: Mapped[TradeSide] = mapped_column(Enum(TradeSide))
    is_paper: Mapped[bool] = mapped_column(Boolean, default=True)

    # Order details
    contracts: Mapped[int] = mapped_column(Integer)
    price_per_contract: Mapped[float] = mapped_column(Float)  # cents
    total_cost: Mapped[float] = mapped_column(Float)  # USD

    # Kalshi order ID (null for paper trades)
    kalshi_order_id: Mapped[Optional[str]] = mapped_column(String(100), nullable=True)

    # Outcome (filled when market closes)
    outcome: Mapped[TradeOutcome] = mapped_column(
        Enum(TradeOutcome), default=TradeOutcome.pending
    )
    resolved_at: Mapped[Optional[datetime]] = mapped_column(DateTime(timezone=True), nullable=True)
    payout: Mapped[Optional[float]] = mapped_column(Float, nullable=True)  # USD received
    pnl: Mapped[Optional[float]] = mapped_column(Float, nullable=True)     # payout - cost

    cycle: Mapped["TradingCycle"] = relationship(back_populates="trade")
